### ISSUE TITLE
Publish package to debian repository

### ISSUE THREAD

**Issue by tristanlatr** [yeraydiazdiaz/lunr.py#113]
Hi @yeraydiazdiaz, 

pydoctor is packaged in the debian reposoitory here: https://tracker.debian.org/pkg/pydoctor

I was wonderring if you'de want to add a `python-lunr` package to the tracker ? Not that [node-lunr](https://tracker.debian.org/pkg/node-lunr) package exists, so it makes sens to add `python-lunr`. 

I you're not willing to initiate such process, I'll vendor lunr.py inside pydoctor, and that's OK too.

Tell me if what you think,

**Comment by yeraydiazdiaz** [comment]
Hi @tristanlatr, I'm not particularly interested in doing that to be honest not being a user of Debian myself, but if anyone more familiar with the process would like to package lunr.py I'm not against that. Of course, you're more than welcome to vendor lunr.py in pydoctor as you mention.
