### ISSUE TITLE
Any chance to support 'zh' (Chinese) language? (maybe I could help)

### ISSUE THREAD

**Issue by huanlin** [yeraydiazdiaz/lunr.py#128]
Hi,
I'm using Mkdocs with mkdocs-static-i18n plugin, and I found language `zh` doesn't work because Lunr does not support it.
Any chance to add `zh` ?
If not too difficult, maybe I could help. (I'm not a Python guy, but I would try my best)

**Comment by yeraydiazdiaz** [comment]
Hi @huanlin, as stated in the README lunr.py language support depends on the [NTLK stemmers](https://www.nltk.org/api/nltk.stem.SnowballStemmer.html?highlight=languages#nltk.stem.SnowballStemmer.languages) which do not support Chinese at the moment. If they ever do I would consider a PR for adding said support.
