### ISSUE TITLE
0.7.0 build findings

### ISSUE THREAD

**Issue by bollwyvl** [yeraydiazdiaz/lunr.py#134]
Congrats on `0.7.0`, and thanks for `lunr.py`!

Some quick notes working downstream on [conda-forge](https://github.com/conda-forge/lunr-feedstock/pull/15):
- the [PyPI readme](https://pypi.org/project/lunr/0.7.0) is blank
- the `javascript` folder for acceptance tests is not included

Neither of these were blocking that PR, as we already pulled the JS from the GitHub snapshot and don't interact with the PyPI HTML, but these might be inconvenient for users and other downstreams.

Some other little things:
- #120 would really be quite lovely! 
  - Missing that ability has tempted me to see if `lunr.js` will run under [js2py](https://pypi.org/project/Js2Py) to get richer results back, even if it was slower/bigger to generate :blush:
  - if you had any guidance on where that might be injected, i'd be happy to try my hand at it
- `lunr.py` (with `nltk`) works _great_ in [pyodide](https://github.com/pyodide/pyodide/), which means it also works quite well in [jupyterlite](https://github.com/jupyterlite/jupyterlite/)
  - live demos could be added to the documentation site, either "the hard way" through manually building a site and adding it to `html_static_paths`, or through the [sphinx plugin](https://github.com/jupyterlite/jupyterlite-sphinx/)

Thanks again!

**Comment by yeraydiazdiaz** [comment]
Hey @bollwyvl, thanks for the heads up, I'll try to amend the readme and the missing folder soon which should be straight forward.

I'll see if I have time to look into #120 as well, though I'm a bit tight on time.

**Comment by bollwyvl** [comment]
Thanks again, just shipped `0.7.0.post1`, using only the sdist :tada:
