### ISSUE TITLE
Add support for metadata whitelisting

### ISSUE THREAD

**Issue by jimkohl** [yeraydiazdiaz/lunr.py#77]
lunr.js supports [metadata whitelisting](https://lunrjs.com/guides/customising.html) look under the TOKEN META-DATA section.

This is useful for adding fields into the index so that when a search matches, more info the key is available for presentation or other purposes.

For example, can return some things like type of thing found (so you could display an icon) or a creation date for sorting results, etc. 

Looks like there is another issue for pipeline support; this would also require pipeline support.

Thanks for a great tool.
jim

**Comment by yeraydiazdiaz** [comment]
[Lunr 0.6.0 has been released](https://pypi.org/project/lunr/0.6.0/) including support for [metadata whitelisting](https://lunr.readthedocs.io/en/latest/customisation.html#token-meta-data).

Let me know how you get on 🙂

**Comment by jimkohl** [comment]
Veray  thanks for doing this!
It’s on my list for today. 
Jim
