### ISSUE TITLE
Update existing index?

### ISSUE THREAD

**Issue by chrisspen** [yeraydiazdiaz/lunr.py#79]
Looking at the code in `__main__.py`, it looks like an index has to be created in a batch, and can't be incrementally updated. Is this correct?

Is there any way to add a new document to an index without having to retrieve all documents and pass them in as a list to `lunr()`?

**Comment by yeraydiazdiaz** [comment]
Hi @chrisspen, that's right, indices need to be created with the complete set of documents.

**Comment by Uzay-G** [comment]
It'd be nice if it was possible to update the indexes instead of regenerating them.
