### ISSUE TITLE
Lunr.py Performance

### ISSUE THREAD

**Issue by GabrielGhe** [yeraydiazdiaz/lunr.py#86]
I ran the same query on lunr.js and lunr.py to test the performance and the python implementation is 4x slower.

I think it could be fixed by using multiprocessing but it still might not match javascript's speed.

**Comment by yeraydiazdiaz** [comment]
Hi @GabrielGhe, I noticed that too, but performance parity with lunr.js was never a design goal.

The task itself is pretty much exactly where pure Python just doesn't shine compared to JavaScript, Anthony Shaw describes it quite well in his [PyCon US talk](https://www.youtube.com/watch?v=I4nkgJdVZFA).

That being said I certainly have relative performance between versions in mind as I've developed lunr.py. I've setup benchmarks and done some investigation on using extensions, but the development overhead is much too high for a performance benefit that most users probably wouldn't notice or care.
